---

- name: Make Sure Directories Exists
  file:
    path: "{{ template.dir }}"
    state: directory
    mode: "{{ template.dir_mode | default('0755') }}"
  tags:
    - setup_config

- name: Reset Template Variables
  set_fact:
    template_variables: "{{ template.variables | default({}) }}"
  tags:
    - setup_config

- name: Create Files From Templates
  template:
    src: "{{ template.src }}"
    dest: "{{ template.dir }}/{{ template.name }}"
    owner: "{{ template.owner | default(omit) }}"
    group: "{{ template.group | default(omit) }}"
    mode: "{{ template.mode }}"
    backup: yes
  tags:
    - setup_config
  when: template.name is defined
